image: luojinghui/node-yarn:v1.0.0

cache:
  key: template
  paths:
  - node_modules/

before_script:
  - echo "set yarn config start"
  - yarn config set registry http://10.80.84.176:4873/
  - echo "set yarn config end"
  - yarn install
  - whoami
  
stages:
  - test
  - dev

test:
  stage: test
  tags:
    - docker-deploy-test
  only:
    - master
  script:
   - yarn test

build-dev:
  stage: dev
  environment:
    # 指定当前job的运行环境，$CI_COMMIT_REF_NAME代表当前分支名
    name: dev/$CI_COMMIT_REF_NAME
  tags:
    - docker-deploy-test
  only:
    - master  
  script:
    - yarn dll
    - yarn build
